#+options: toc:nil  pri:t title:nil num:nil
#+language: de

* .spacemacs.d

  Configuration files for [[http://spacemacs.org][spacemacs]]. Checkout the develop branch of
  spacemacs into =.emacs.d= and this repo into =.spacemacs.d=

* Layers

  Configured layers consist mainly of

  - org mode (including org roam)
  - common lisp (requires roswell)
  - scala

 and other helper layers.

* Import keyboard shortcuts

** org-mode/org-roam

   - =SPC a o r d t= :: adds a journal entry for the day
   - =SPC a o r f= :: find roam files
   - =SPC a o r i= :: insert roam link
   - =SPC a o o n= :: view org agenda agenda and todo items
   - =M-S-Ret= :: enter a new todo item
   - =C-C C-q= :: set tag for note/task/headline
   - =, s S= :: Sort entries under headline
   - =M-Ret M-Ret= :: insert an element of the same type


** Task clocking
   [[https://orgmode.org/manual/Clocking-commands.html#Clocking-commands]]

   - =C-c C-x C-i= :: Clock in
   - =C-c C-x C-o= :: Clock out
   - =C-c C-x C-q= :: Clock cancel
   - =C-c C-x C-d= :: display clock

** Git

   - =SPC g s= :: git status (? for command list)
   - =SPC g m= :: git magic dispatch (transient git state)

* Org

  Org is configured to have its org files and org agenda files in =~/org=.
  Possibly sym link this with a drop box account.

* TODOS
** TODO Investigate locale
   - Note taken on [2021-01-19 Di 14:38] \\
     Inspect environment with =M-x getenv=.
   - Note taken on [2021-01-18 Mo 16:35] \\
     GUI emacs and console emacs use different date formatting in journal mode. Investigate why.
** DONE Revert to org-journal
   CLOSED: [2021-01-18 Mo 16:34] SCHEDULED: <2021-01-22 Fr>

* Dependencies
  Script to install dependencies:

    #+begin_example
    brew tap d12frosted/emacs-plus
    brew install emacs-plus@27
    brew install roswell basictex font-fira-code
    brew services start emacs-plus@27

    # Install EmacsClient.app from org directory
    # Install org capture chrome extension from Google Web Store
    
    sudo tlmgr update --self
    sudo tlmgr install koma-script
    sudo tlmgr install wrapfig
    sudo tlmgr install capt-of

    # roswell commands to install sbcl, slime...
    #+end_example
